import type { Metadata } from 'next';
import '@/styles/globals.scss';
import { quicksand } from './fonts';

export const metadata: Metadata = {
  title: 'Femi Balogun',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
  );
}
